version: '2'
services:
  best-ever:
    container_name: best-ever
    build: .
    volumes:
      - .:/go/src/github.com/jsadwith/BestEver
    command: sh -c "CompileDaemon -command=./BestEver"
    environment:
      PORT: 80

      DB_POSTGRES_HOST: "192.168.1.194"
      DB_POSTGRES_NAME: "bestever"
      DB_POSTGRES_USER: "jsadwith"
      DB_POSTGRES_PASSWORD: ""
      DB_POSTGRES_LOG: 1
    networks:
      - "jrs.io"
    expose:
      - 80
networks:
  jrs.io:
    external:
      name: jrs.io
